#!/bin/sh
set -e

case "$1" in
    remove)
        # Restore original Calamares icon 
        dpkg-divert --quiet --rename --package calamares-settings-vanilla \
                    --remove /usr/share/applications/calamares.desktop
    ;;
esac

#DEBHELPER#
