#!/bin/bash

selectedboard=$(cat /etc/default/keyboard | grep XKBLAYOUT= | cut -f2 -d\")

echo 'KEYMAP='$selectedboard | tee /etc/vconsole.conf

for d in /home/*/ ; do
    mkdir -p $d.config/fcitx5/
    touch $d.config/fcitx5/profile
    echo '[Groups/0]
# Group Name
Name=Default
# Layout
Default Layout='$selectedboard'
# Default Input Method
DefaultIM=keyboard-'$selectedboard'

[Groups/0/Items/0]
# Name
Name=keyboard-'$selectedboard'
# Layout
Layout=

[GroupOrder]
0=Default' >> $d.config/fcitx5/profile

if test -f "$d.config/hypr/hyprland.conf"; then
    rpl='#kb_layout='
    wth='kb_layout='$selectedboard
    sed -i -e "s/$rpl/$wth/g" $d.config/hypr/hyprland.conf
    sed -e 's [initial_session] #[initial_session] g' -i /etc/greetd/config.toml
    sed -e 's\user = "pikaos"\#user = "pikaos"\g' -i /etc/greetd/config.toml
    sed -e 's\command = "Hyprland"\#command = "Hyprland"\g' -i /etc/greetd/config.toml
fi
done

if command -v fcitx5 &> /dev/null
then
    fcitx5 -d &
fi
