#! /usr/bin/bash
BOOT_BLOCK=$(lsblk -ndo pkname $(df -P "/boot" | awk 'END{print $1}'))
ROOT_UUID=$(findmnt --fstab -T / -o SOURCE | tail +2)
ROOT_FLAGS=$(findmnt --fstab -T / -o Options | tail +2)

if [ -d /sys/firmware/efi ]
then 
	echo "UEFI Detected! Installing systemd-boot"
	for i in $(/usr/bin/apt --installed list 2>/dev/null | grep grub | cut -d"/" -f1 | grep -vi grub-common) ; do apt remove -y $i || echo "no action needed for $i" ; done || true
	bootctl install || true
	SDB_EFI=$(bootctl -p) || true
	cp -f /etc/calamares/config/loader.conf $SDB_EFI/loader/loader.conf || true
	mkdir -p /tmp/update-systemd-boot || true
	echo "root=$ROOT_UUID rootflags=$ROOT_FLAGS quiet splash bgrt_disable $vt_handoff" > /tmp/update-systemd-boot/options || true
	sudo update-systemd-boot -o || true
	sudo update-systemd-boot -x || true
else
	echo "Legacy BIOS Detected! Installing grub"
	/usr/bin/apt install --yes --option Acquire::Retries=5 --option Acquire::http::Timeout=100 /var/cache/apt/archives/grub-gfxpayload-lists*.deb /var/cache/apt/archives/grub-pc*.deb /var/cache/apt/archives/grub-pc-bin*.deb /var/cache/apt/archives/grub2-common*.deb --allow-unauthenticated || true
	grub-install --boot-directory=/boot /dev/$BOOT_BLOCK || true
	grub-mkconfig -o /boot/grub/grub.cfg || true
	update-grub || true
fi
